spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3308/Netco_microservices
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rootroot@1045

  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

inventory:
  url: http://localhost:8083
