spring.application.name=product-service
spring.data.mongodb.uri=mongodb://localhost:27017/product-service
server.port=8084
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# 
loki.url=http://localhost:3100/loki/api/v1/push
#eureka.client.service-url.defaulZone=http://localhost:8761/eureka

